name: Build Windows EXE

on:
  workflow_dispatch:   # Run manually from Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name "GSEHS-School-Management" app.py
        shell: powershell

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: GSEHS-School-Management-exe
          path: dist/GSEHS-School-Management.exe
